name: CI

# Trigger on Push to main or any Pull Request
on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  build-test-lint:
    name: Build, Format, Lint, Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        with:
          enable-stack: true
          stack-version: 'latest'

      - name: Cache ~/.stack
        uses: actions/cache@v3
        with:
          path: |
            ~/.stack
            .stack-work
          # Create a new cache whenever stack.yaml or package.yaml changes
          key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml.lock', 'package.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack-

      - name: Build Dependencies
        run: stack build --test --bench --no-run-tests --no-run-benchmarks --only-dependencies

      - name: Build Project
        run: stack build --test --no-run-tests

      - name: Format check (Ormolu)
        run: bash ./scripts/format-check.sh

      - name: Lint (HLint and GHC compiler)
        run: bash ./scripts/lint.sh

      - name: Run Tests
        run: stack test